_pos = getMarkerPos (_this select 0);
_dir = MarkerDir (_this select 0);
_gr = _this select 2;
_xp = _pos select 0;
_yp = _pos select 1;
_ls = [];
_ob = "RHS_M119_WD" createVehicle [_xp + sin (_dir - 90) * 8,_yp + cos (_dir - 90) * 8];
_ob setDir _dir;
_un = _gr createUnit ["rhsusf_usmc_marpat_wd_rifleman_m4", _pos, [], 0, "FORM"];
_un MoveInGunner _ob;
_ls = _ls + [_un];
_un = _gr createUnit ["rhsusf_usmc_marpat_wd_rifleman_m4", _pos, [], 0, "FORM"];
_un MoveInCargo _ob;
_ls = _ls + [_un];
_ob = "RHS_M119_WD" createVehicle [_xp + sin (_dir + 90) * 8,_yp + cos (_dir + 90) * 8];
_ob setDir _dir;
_un = _gr createUnit ["rhsusf_usmc_marpat_wd_rifleman_m4", _pos, [], 0, "FORM"];
_un MoveInGunner _ob;
_ls = _ls + [_un];
_un = _gr createUnit ["rhsusf_usmc_marpat_wd_rifleman_m4", _pos, [], 0, "FORM"];
_un MoveInCargo _ob;
_ls = _ls + [_un];
_ob = "RHS_M2StaticMG_MiniTripod_WD" createVehicle [_xp + sin (_dir - 80) * 14,_yp + cos (_dir - 80) * 14];
_ob setDir _dir;
_un = _gr createUnit ["rhsusf_usmc_marpat_wd_rifleman_m4", _pos, [], 0, "FORM"];
_un MoveInGunner _ob;
_ls = _ls + [_un];
_ob = "RHS_M2StaticMG_MiniTripod_WD" createVehicle [_xp + sin (_dir + 80) * 14,_yp + cos (_dir + 80) * 14];
_ob setDir _dir;
_un = _gr createUnit ["rhsusf_usmc_marpat_wd_rifleman_m4", _pos, [], 0, "FORM"];
_un MoveInGunner _ob;
_ls = _ls + [_un];
_ob = "Mine" createVehicle _pos;
_un = _gr createUnit ["rhsusf_usmc_recon_marpat_wd_officer", _pos, [], 5, "FORM"];
_gr selectLeader _un;
_ls = _ls + [_un];
List_WE_c = List_WE_c + _ls;

